version: '3.4'
services:
  mongo-container:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=
        - MONGO_INITDB_ROOT_PASSWORD=
        - MONGO_USERNAME=
        - MONGO_PASSWORD=
        - MONGO_PORT=27017
        - MONGO_HOSTNAME=localhost
        - MONGO_DB=
        - MONGO_ROOT_USERNAME=
        - MONGO_ROOT_PASSWORD=
        - MONGO_ROOT_DATABASE=
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-entrypoint.db:/docker-entrypoint-initdb.d/"
    command: mongod
